export interface MatchResult {
  id: string;
  taskName: string;
  taskCategory: string;
  assignedVolunteer: string;
  volunteerSkills: string[];
  confidenceScore: number;
  aiReasoning: string;
  status: 'matched' | 'partial' | 'unmatched';
}

export interface Volunteer {
  id: string;
  name: string;
  role: string;
  skills: string[];
  availability: 'available' | 'assigned' | 'on-leave';
  experienceLevel: 'Junior' | 'Mid' | 'Senior' | 'Expert';
  totalMatches: number;
  successRate: number;
  lastActive: string;
  location: string;
  languages: string[];
}

export interface Task {
  id: string;
  name: string;
  category: string;
  requiredSkills: string[];
  priority: 'Critical' | 'High' | 'Medium' | 'Low';
  deadline: string;
  assignedVolunteer: string | null;
  status: 'open' | 'matched' | 'confirmed' | 'completed';
  confidenceScore: number | null;
  estimatedHours: number;
  location: string;
}

export const MOCK_MATCH_RESULTS: MatchResult[] = [
  {
    id: 'match-001',
    taskName: 'Community Health Survey',
    taskCategory: 'Healthcare',
    assignedVolunteer: 'Dr. Sarah Chen',
    volunteerSkills: ['Medical', 'Data Analysis', 'Communication'],
    confidenceScore: 97,
    aiReasoning: 'Perfect skill vector alignment. Medical background + survey experience + bilingual capability matches all task requirements.',
    status: 'matched',
  },
  {
    id: 'match-002',
    taskName: 'Legal Aid Clinic',
    taskCategory: 'Legal',
    assignedVolunteer: 'Marcus Williams',
    volunteerSkills: ['Law', 'Advocacy', 'Documentation'],
    confidenceScore: 92,
    aiReasoning: 'Bar-certified attorney with 4 years pro-bono experience. Availability window aligns with clinic schedule.',
    status: 'matched',
  },
  {
    id: 'match-003',
    taskName: 'Youth Coding Workshop',
    taskCategory: 'Education',
    assignedVolunteer: 'Priya Patel',
    volunteerSkills: ['Software Engineering', 'Teaching', 'Python'],
    confidenceScore: 88,
    aiReasoning: 'Strong technical background with prior teaching experience. Minor gap: no formal pedagogy certification.',
    status: 'matched',
  },
  {
    id: 'match-004',
    taskName: 'Disaster Relief Logistics',
    taskCategory: 'Emergency',
    assignedVolunteer: 'James Okonkwo',
    volunteerSkills: ['Logistics', 'Leadership', 'First Aid'],
    confidenceScore: 79,
    aiReasoning: 'Logistics expertise confirmed. Leadership score moderate. Recommend pairing with senior coordinator for first deployment.',
    status: 'partial',
  },
  {
    id: 'match-005',
    taskName: 'Financial Literacy Program',
    taskCategory: 'Finance',
    assignedVolunteer: 'Elena Vasquez',
    volunteerSkills: ['Accounting', 'Public Speaking'],
    confidenceScore: 74,
    aiReasoning: 'Accounting skills match core requirement. Public speaking score adequate. No prior NGO facilitation experience detected.',
    status: 'partial',
  },
  {
    id: 'match-006',
    taskName: 'Mental Health Support Line',
    taskCategory: 'Healthcare',
    assignedVolunteer: 'Dr. Amir Hassan',
    volunteerSkills: ['Psychology', 'Counseling', 'Crisis Intervention'],
    confidenceScore: 95,
    aiReasoning: 'Licensed psychologist with crisis intervention certification. Optimal match across all weighted skill dimensions.',
    status: 'matched',
  },
  {
    id: 'match-007',
    taskName: 'Environmental Audit',
    taskCategory: 'Environment',
    assignedVolunteer: 'Lena Müller',
    volunteerSkills: ['Environmental Science', 'Data Collection'],
    confidenceScore: 65,
    aiReasoning: 'Environmental science degree present but audit-specific certifications absent. Confidence penalized for missing ISO 14001 knowledge.',
    status: 'partial',
  },
  {
    id: 'match-008',
    taskName: 'Refugee Language Support',
    taskCategory: 'Social Services',
    assignedVolunteer: 'Fatima Al-Rashid',
    volunteerSkills: ['Arabic', 'French', 'Social Work'],
    confidenceScore: 91,
    aiReasoning: 'Trilingual social worker with direct refugee support experience. Scheduling compatibility verified.',
    status: 'matched',
  },
  {
    id: 'match-009',
    taskName: 'Food Bank Distribution',
    taskCategory: 'Community',
    assignedVolunteer: 'Tomás Rivera',
    volunteerSkills: ['Logistics', 'Physical Labor', 'Team Coordination'],
    confidenceScore: 83,
    aiReasoning: 'Strong physical capability and prior food bank volunteering. Minor gap in inventory management software.',
    status: 'matched',
  },
  {
    id: 'match-010',
    taskName: 'Senior Tech Literacy Class',
    taskCategory: 'Education',
    assignedVolunteer: 'Nadia Osei',
    volunteerSkills: ['IT Support', 'Patience', 'Communication'],
    confidenceScore: 68,
    aiReasoning: 'IT background confirmed. No prior senior outreach experience. Patience metric below threshold. Recommend supervised session.',
    status: 'partial',
  },
  {
    id: 'match-011',
    taskName: 'Grant Writing Support',
    taskCategory: 'Administration',
    assignedVolunteer: 'Unassigned',
    volunteerSkills: [],
    confidenceScore: 0,
    aiReasoning: 'No volunteer with grant writing + nonprofit compliance skills found in current roster. Manual assignment required.',
    status: 'unmatched',
  },
  {
    id: 'match-012',
    taskName: 'Child Nutrition Workshop',
    taskCategory: 'Healthcare',
    assignedVolunteer: 'Dr. Yuki Tanaka',
    volunteerSkills: ['Pediatrics', 'Nutrition', 'Public Health'],
    confidenceScore: 94,
    aiReasoning: 'Pediatric dietitian with public health certification. All required competencies verified. High confidence allocation.',
    status: 'matched',
  },
];

export const CONFIDENCE_DISTRIBUTION = [
  { range: '90–100%', count: 5, fill: '#10b981' },
  { range: '80–89%', count: 3, fill: '#34d399' },
  { range: '70–79%', count: 2, fill: '#f59e0b' },
  { range: '60–69%', count: 2, fill: '#f97316' },
  { range: '<60%', count: 1, fill: '#ef4444' },
];

export const MATCH_TREND = [
  { date: 'Mar 15', matches: 18, avgConfidence: 82 },
  { date: 'Mar 22', matches: 24, avgConfidence: 79 },
  { date: 'Mar 29', matches: 31, avgConfidence: 84 },
  { date: 'Apr 5', matches: 27, avgConfidence: 81 },
  { date: 'Apr 10', matches: 34, avgConfidence: 86 },
];

export const MOCK_VOLUNTEERS: Volunteer[] = [
  {
    id: 'vol-001',
    name: 'Dr. Sarah Chen',
    role: 'Medical Professional',
    skills: ['Medical', 'Data Analysis', 'Communication', 'Mandarin'],
    availability: 'assigned',
    experienceLevel: 'Expert',
    totalMatches: 47,
    successRate: 96,
    lastActive: '2026-04-10',
    location: 'San Francisco, CA',
    languages: ['English', 'Mandarin'],
  },
  {
    id: 'vol-002',
    name: 'Marcus Williams',
    role: 'Attorney',
    skills: ['Law', 'Advocacy', 'Documentation', 'Negotiation'],
    availability: 'assigned',
    experienceLevel: 'Expert',
    totalMatches: 38,
    successRate: 94,
    lastActive: '2026-04-09',
    location: 'New York, NY',
    languages: ['English', 'Spanish'],
  },
  {
    id: 'vol-003',
    name: 'Priya Patel',
    role: 'Software Engineer',
    skills: ['Python', 'Teaching', 'JavaScript', 'Data Science'],
    availability: 'assigned',
    experienceLevel: 'Senior',
    totalMatches: 22,
    successRate: 91,
    lastActive: '2026-04-10',
    location: 'Austin, TX',
    languages: ['English', 'Hindi', 'Gujarati'],
  },
  {
    id: 'vol-004',
    name: 'James Okonkwo',
    role: 'Logistics Coordinator',
    skills: ['Logistics', 'Leadership', 'First Aid', 'Supply Chain'],
    availability: 'assigned',
    experienceLevel: 'Mid',
    totalMatches: 15,
    successRate: 78,
    lastActive: '2026-04-08',
    location: 'Chicago, IL',
    languages: ['English', 'Igbo'],
  },
  {
    id: 'vol-005',
    name: 'Elena Vasquez',
    role: 'Financial Analyst',
    skills: ['Accounting', 'Public Speaking', 'Excel', 'Budgeting'],
    availability: 'assigned',
    experienceLevel: 'Mid',
    totalMatches: 11,
    successRate: 74,
    lastActive: '2026-04-07',
    location: 'Miami, FL',
    languages: ['English', 'Spanish', 'Portuguese'],
  },
  {
    id: 'vol-006',
    name: 'Dr. Amir Hassan',
    role: 'Clinical Psychologist',
    skills: ['Psychology', 'Counseling', 'Crisis Intervention', 'CBT'],
    availability: 'assigned',
    experienceLevel: 'Expert',
    totalMatches: 53,
    successRate: 97,
    lastActive: '2026-04-10',
    location: 'Boston, MA',
    languages: ['English', 'Arabic', 'Farsi'],
  },
  {
    id: 'vol-007',
    name: 'Lena Müller',
    role: 'Environmental Scientist',
    skills: ['Environmental Science', 'Data Collection', 'GIS', 'Reporting'],
    availability: 'available',
    experienceLevel: 'Mid',
    totalMatches: 8,
    successRate: 68,
    lastActive: '2026-04-06',
    location: 'Seattle, WA',
    languages: ['English', 'German'],
  },
  {
    id: 'vol-008',
    name: 'Fatima Al-Rashid',
    role: 'Social Worker',
    skills: ['Arabic', 'French', 'Social Work', 'Case Management'],
    availability: 'assigned',
    experienceLevel: 'Senior',
    totalMatches: 29,
    successRate: 92,
    lastActive: '2026-04-10',
    location: 'Detroit, MI',
    languages: ['English', 'Arabic', 'French'],
  },
  {
    id: 'vol-009',
    name: 'Tomás Rivera',
    role: 'Community Organizer',
    skills: ['Logistics', 'Physical Labor', 'Team Coordination', 'Spanish'],
    availability: 'assigned',
    experienceLevel: 'Mid',
    totalMatches: 19,
    successRate: 83,
    lastActive: '2026-04-09',
    location: 'Los Angeles, CA',
    languages: ['English', 'Spanish'],
  },
  {
    id: 'vol-010',
    name: 'Nadia Osei',
    role: 'IT Support Specialist',
    skills: ['IT Support', 'Communication', 'Hardware', 'Windows'],
    availability: 'available',
    experienceLevel: 'Junior',
    totalMatches: 5,
    successRate: 68,
    lastActive: '2026-04-05',
    location: 'Atlanta, GA',
    languages: ['English', 'Twi'],
  },
  {
    id: 'vol-011',
    name: 'Dr. Yuki Tanaka',
    role: 'Pediatric Dietitian',
    skills: ['Pediatrics', 'Nutrition', 'Public Health', 'Workshop Facilitation'],
    availability: 'assigned',
    experienceLevel: 'Expert',
    totalMatches: 41,
    successRate: 95,
    lastActive: '2026-04-10',
    location: 'Portland, OR',
    languages: ['English', 'Japanese'],
  },
  {
    id: 'vol-012',
    name: 'Kofi Mensah',
    role: 'Grant Writer',
    skills: ['Grant Writing', 'Nonprofit Compliance', 'Fundraising', 'Research'],
    availability: 'on-leave',
    experienceLevel: 'Senior',
    totalMatches: 33,
    successRate: 89,
    lastActive: '2026-03-28',
    location: 'Washington, DC',
    languages: ['English', 'French', 'Twi'],
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: 'task-001',
    name: 'Community Health Survey',
    category: 'Healthcare',
    requiredSkills: ['Medical', 'Data Analysis', 'Communication'],
    priority: 'High',
    deadline: '2026-04-18',
    assignedVolunteer: 'Dr. Sarah Chen',
    status: 'matched',
    confidenceScore: 97,
    estimatedHours: 8,
    location: 'San Francisco, CA',
  },
  {
    id: 'task-002',
    name: 'Legal Aid Clinic',
    category: 'Legal',
    requiredSkills: ['Law', 'Advocacy', 'Documentation'],
    priority: 'Critical',
    deadline: '2026-04-15',
    assignedVolunteer: 'Marcus Williams',
    status: 'confirmed',
    confidenceScore: 92,
    estimatedHours: 12,
    location: 'New York, NY',
  },
  {
    id: 'task-003',
    name: 'Youth Coding Workshop',
    category: 'Education',
    requiredSkills: ['Software Engineering', 'Teaching', 'Python'],
    priority: 'Medium',
    deadline: '2026-04-22',
    assignedVolunteer: 'Priya Patel',
    status: 'matched',
    confidenceScore: 88,
    estimatedHours: 6,
    location: 'Austin, TX',
  },
  {
    id: 'task-004',
    name: 'Disaster Relief Logistics',
    category: 'Emergency',
    requiredSkills: ['Logistics', 'Leadership', 'First Aid'],
    priority: 'Critical',
    deadline: '2026-04-12',
    assignedVolunteer: 'James Okonkwo',
    status: 'matched',
    confidenceScore: 79,
    estimatedHours: 24,
    location: 'Chicago, IL',
  },
  {
    id: 'task-005',
    name: 'Financial Literacy Program',
    category: 'Finance',
    requiredSkills: ['Accounting', 'Public Speaking', 'Facilitation'],
    priority: 'Medium',
    deadline: '2026-04-25',
    assignedVolunteer: 'Elena Vasquez',
    status: 'matched',
    confidenceScore: 74,
    estimatedHours: 10,
    location: 'Miami, FL',
  },
  {
    id: 'task-006',
    name: 'Mental Health Support Line',
    category: 'Healthcare',
    requiredSkills: ['Psychology', 'Counseling', 'Crisis Intervention'],
    priority: 'Critical',
    deadline: '2026-04-14',
    assignedVolunteer: 'Dr. Amir Hassan',
    status: 'confirmed',
    confidenceScore: 95,
    estimatedHours: 20,
    location: 'Remote',
  },
  {
    id: 'task-007',
    name: 'Environmental Audit',
    category: 'Environment',
    requiredSkills: ['Environmental Science', 'Data Collection', 'ISO 14001'],
    priority: 'Low',
    deadline: '2026-05-01',
    assignedVolunteer: 'Lena Müller',
    status: 'matched',
    confidenceScore: 65,
    estimatedHours: 16,
    location: 'Seattle, WA',
  },
  {
    id: 'task-008',
    name: 'Refugee Language Support',
    category: 'Social Services',
    requiredSkills: ['Arabic', 'French', 'Social Work'],
    priority: 'High',
    deadline: '2026-04-17',
    assignedVolunteer: 'Fatima Al-Rashid',
    status: 'matched',
    confidenceScore: 91,
    estimatedHours: 14,
    location: 'Detroit, MI',
  },
  {
    id: 'task-009',
    name: 'Food Bank Distribution',
    category: 'Community',
    requiredSkills: ['Logistics', 'Physical Labor', 'Team Coordination'],
    priority: 'High',
    deadline: '2026-04-13',
    assignedVolunteer: 'Tomás Rivera',
    status: 'confirmed',
    confidenceScore: 83,
    estimatedHours: 8,
    location: 'Los Angeles, CA',
  },
  {
    id: 'task-010',
    name: 'Senior Tech Literacy Class',
    category: 'Education',
    requiredSkills: ['IT Support', 'Patience', 'Communication'],
    priority: 'Medium',
    deadline: '2026-04-20',
    assignedVolunteer: 'Nadia Osei',
    status: 'matched',
    confidenceScore: 68,
    estimatedHours: 6,
    location: 'Atlanta, GA',
  },
  {
    id: 'task-011',
    name: 'Grant Writing Support',
    category: 'Administration',
    requiredSkills: ['Grant Writing', 'Nonprofit Compliance', 'Research'],
    priority: 'Critical',
    deadline: '2026-04-16',
    assignedVolunteer: null,
    status: 'open',
    confidenceScore: null,
    estimatedHours: 20,
    location: 'Remote',
  },
  {
    id: 'task-012',
    name: 'Child Nutrition Workshop',
    category: 'Healthcare',
    requiredSkills: ['Pediatrics', 'Nutrition', 'Public Health'],
    priority: 'High',
    deadline: '2026-04-19',
    assignedVolunteer: 'Dr. Yuki Tanaka',
    status: 'matched',
    confidenceScore: 94,
    estimatedHours: 8,
    location: 'Portland, OR',
  },
  {
    id: 'task-013',
    name: 'Water Sanitation Training',
    category: 'Environment',
    requiredSkills: ['Environmental Science', 'Training', 'Public Health'],
    priority: 'High',
    deadline: '2026-04-21',
    assignedVolunteer: null,
    status: 'open',
    confidenceScore: null,
    estimatedHours: 12,
    location: 'Remote',
  },
  {
    id: 'task-014',
    name: 'Fundraising Gala Planning',
    category: 'Administration',
    requiredSkills: ['Event Planning', 'Fundraising', 'Communication'],
    priority: 'Medium',
    deadline: '2026-04-30',
    assignedVolunteer: null,
    status: 'open',
    confidenceScore: null,
    estimatedHours: 30,
    location: 'Washington, DC',
  },
];